# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "980aeb4e6505f020ced5920fa3578b7d"
name = "MultiChannel Commerce"
application_url = "https://multichannel-commerce-ruddy.vercel.app"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory"

[auth]
redirect_urls = [
  "http://localhost:5000/api/integrations/shopify/callback",
  "https://multichannel-commerce-hoee.onrender.com/api/integrations/shopify/callback"
]

[webhooks]
api_version = "2026-07"

[app_proxy]
url = "https://multichannel-commerce-ruddy.vercel.app"
subpath = "multichannel"
prefix = "apps"